require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe QuestionFieldsController do

  # This should return the minimal set of attributes required to create a valid
  # QuestionField. As you add validations to QuestionField, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "answer" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # QuestionFieldsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all question_fields as @question_fields" do
      question_field = QuestionField.create! valid_attributes
      get :index, {}, valid_session
      assigns(:question_fields).should eq([question_field])
    end
  end

  describe "GET show" do
    it "assigns the requested question_field as @question_field" do
      question_field = QuestionField.create! valid_attributes
      get :show, {:id => question_field.to_param}, valid_session
      assigns(:question_field).should eq(question_field)
    end
  end

  describe "GET new" do
    it "assigns a new question_field as @question_field" do
      get :new, {}, valid_session
      assigns(:question_field).should be_a_new(QuestionField)
    end
  end

  describe "GET edit" do
    it "assigns the requested question_field as @question_field" do
      question_field = QuestionField.create! valid_attributes
      get :edit, {:id => question_field.to_param}, valid_session
      assigns(:question_field).should eq(question_field)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new QuestionField" do
        expect {
          post :create, {:question_field => valid_attributes}, valid_session
        }.to change(QuestionField, :count).by(1)
      end

      it "assigns a newly created question_field as @question_field" do
        post :create, {:question_field => valid_attributes}, valid_session
        assigns(:question_field).should be_a(QuestionField)
        assigns(:question_field).should be_persisted
      end

      it "redirects to the created question_field" do
        post :create, {:question_field => valid_attributes}, valid_session
        response.should redirect_to(QuestionField.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved question_field as @question_field" do
        # Trigger the behavior that occurs when invalid params are submitted
        QuestionField.any_instance.stub(:save).and_return(false)
        post :create, {:question_field => { "answer" => "invalid value" }}, valid_session
        assigns(:question_field).should be_a_new(QuestionField)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        QuestionField.any_instance.stub(:save).and_return(false)
        post :create, {:question_field => { "answer" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested question_field" do
        question_field = QuestionField.create! valid_attributes
        # Assuming there are no other question_fields in the database, this
        # specifies that the QuestionField created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        QuestionField.any_instance.should_receive(:update_attributes).with({ "answer" => "MyString" })
        put :update, {:id => question_field.to_param, :question_field => { "answer" => "MyString" }}, valid_session
      end

      it "assigns the requested question_field as @question_field" do
        question_field = QuestionField.create! valid_attributes
        put :update, {:id => question_field.to_param, :question_field => valid_attributes}, valid_session
        assigns(:question_field).should eq(question_field)
      end

      it "redirects to the question_field" do
        question_field = QuestionField.create! valid_attributes
        put :update, {:id => question_field.to_param, :question_field => valid_attributes}, valid_session
        response.should redirect_to(question_field)
      end
    end

    describe "with invalid params" do
      it "assigns the question_field as @question_field" do
        question_field = QuestionField.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        QuestionField.any_instance.stub(:save).and_return(false)
        put :update, {:id => question_field.to_param, :question_field => { "answer" => "invalid value" }}, valid_session
        assigns(:question_field).should eq(question_field)
      end

      it "re-renders the 'edit' template" do
        question_field = QuestionField.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        QuestionField.any_instance.stub(:save).and_return(false)
        put :update, {:id => question_field.to_param, :question_field => { "answer" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested question_field" do
      question_field = QuestionField.create! valid_attributes
      expect {
        delete :destroy, {:id => question_field.to_param}, valid_session
      }.to change(QuestionField, :count).by(-1)
    end

    it "redirects to the question_fields list" do
      question_field = QuestionField.create! valid_attributes
      delete :destroy, {:id => question_field.to_param}, valid_session
      response.should redirect_to(question_fields_url)
    end
  end

end
